name: Build and Deploy Script for Angular app
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set user email
        run: git config --global user.email "deploy@bot.com"
      - name: Set user name
        run: git config --global user.name "deploy@bot"

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.7.1

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run buildProd
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

#      - name: Deploy to gh pages
#        run: |
#          npx angular-cli-ghpages --dir=dist/your-angular-app
